# Generated by Django 4.1.7 on 2023-05-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=122)),
                ('quantity', models.CharField(max_length=122)),
                ('productCode', models.CharField(max_length=122)),
                ('description', models.CharField(max_length=122)),
                ('image1', models.CharField(max_length=122)),
                ('image2', models.CharField(max_length=122)),
                ('image3', models.CharField(max_length=122)),
                ('image4', models.CharField(max_length=122)),
                ('image5', models.CharField(max_length=122)),
                ('image6', models.CharField(max_length=122)),
            ],
        ),
    ]
