# Generated by Django 4.1.7 on 2023-05-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
