# Generated by Django 4.1.7 on 2023-05-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_product_category_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=122)),
                ('productcode', models.CharField(max_length=122)),
                ('productName', models.CharField(max_length=122)),
                ('quantity', models.CharField(max_length=122)),
            ],
        ),
    ]
