# Generated by Django 4.1.7 on 2023-05-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
