# Generated by Django 4.1.7 on 2023-05-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_alter_order_now_code_alter_order_now_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_now',
            name='code',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='order_now',
            name='price',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='order_now',
            name='productName',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='order_now',
            name='quantity',
            field=models.JSONField(),
        ),
    ]
