# Generated by Django 4.1.7 on 2023-05-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_alter_order_now_code_alter_order_now_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_now',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_now',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
