# Generated by Django 4.1.7 on 2023-05-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_order_now_date_order_now_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_now',
            name='code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_now',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_now',
            name='price',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_now',
            name='productName',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_now',
            name='quantity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
