# Generated by Django 4.1.7 on 2023-06-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_alter_signup_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Shop_name',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
