# Generated by Django 4.1.7 on 2023-06-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_signup_shop_name_signup_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Phone',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
