# Generated by Django 4.1.7 on 2023-06-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_signup_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='cordinate',
        ),
    ]
