# Generated by Django 4.1.7 on 2023-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0019_remove_signup_cordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='vemail',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_now',
            name='vemail',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vemail',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
