# Generated by Django 4.1.7 on 2023-06-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0020_cart_vemail_order_now_vemail_product_vemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_now',
            name='vemail',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
