# Generated by Django 4.1.7 on 2023-06-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0021_alter_order_now_vemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vemail',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
