# Generated by Django 4.1.7 on 2023-06-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0023_bidding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=255)),
                ('Message', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
            ],
        ),
    ]
