# Generated by Django 4.1.7 on 2023-06-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0024_bidding_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=122)),
                ('Phone', models.CharField(max_length=122)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
