# Generated by Django 4.1.7 on 2023-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0025_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_vendors', models.CharField(max_length=255)),
                ('email_customer', models.CharField(max_length=255)),
                ('drop_down', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='order_now',
            name='status',
            field=models.CharField(default='Delivered', max_length=50),
        ),
    ]
