# Generated by Django 4.1.7 on 2023-06-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0026_feedback_alter_order_now_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding_view',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
